### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by irfanjunaid** [ABCDFAS/dell-vostro-3578-hackintosh-clover-efi#2]
Hi,
I am newbie and trying to Hackintosh my Vostro 3578. Please advise and help!

**Comment by ABCDFAS** [comment]
What’s your problem ?

**Comment by irfanjunaid** [comment]
Is your Hackintosh stable enough for daily use?

**Comment by ABCDFAS** [comment]
Yes. It’s enough for daily use.

**Comment by rasberrychiller** [comment]
is your hackintosh support wifi and facetime?
and do i need to patch DSDP after installing ?

**Comment by ABCDFAS** [comment]
It’s supported. But you need to change wifi with BCM94360cs2, it can works normal .
